IPLManagementSystemMVC/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
namespace IPLManagementSystemMVC.Models
{
    public class LoginViewModel
    {
        public int UserID { get; set; }
        
        [Required(ErrorMessage = "Enter Username")]
        [DataType(DataType.Text)]
        public string Username { get; set; }

        [Required(ErrorMessage = "Enter Password")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
    }
}

IPLManagementSystemMVC/Controllers/HomePageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using IPLManagementSystemMVC.Models;
namespace IPLManagementSystemMVC.Controllers
{
    public class HomePageController : Controller
    {
        // For HomePage
        public ActionResult Index()
        {
            return View();
        }

        //User Login
        public ActionResult Login()
        {
            return View();
        }
        [OutputCache(Duration = 60, VaryByParam = "none")]
        [HttpPost]
        public ActionResult Login(LoginViewModel login)
        {
            //Refer LoginController in WebApi Controllers
            using (HttpClient client = new HttpClient())
            {
                //Select the userdetails and role data as lists to store data
                List<LoginViewModel> userdetails = new List<LoginViewModel>();
                List<RoleViewModel> roleData = new List<RoleViewModel>();
                //Getasync method as it returns the user data which includes password, firstname, lastname, user id
                var result = client.GetAsync("https://localhost:44307/api/login/UserLogin?username=" + login.Username).Result;
                
                if(result.IsSuccessStatusCode)
                {
                    //if user exists 
                    userdetails = result.Content.ReadAsAsync<List<LoginViewModel>>().Result;
                    var useridofclient = userdetails.Select(id => id.UserID).FirstOrDefault();
                    var nameOfUser = userdetails.Select(fn => fn.Firstname).FirstOrDefault() +" "+ userdetails.Select(fn => fn.Lastname).FirstOrDefault();
                    var actualPassword = userdetails.Select(e => e.Password).FirstOrDefault();
                    //verifies password with password present in data base and user entered password
                    if (actualPassword == login.Password)
                    {
                        //if password matches collect role id based on the user id from user roles table
                        var resultOfRoleId = client.GetAsync("https://localhost:44307/api/roleid/" + useridofclient.ToString()).Result;
                        if (resultOfRoleId.IsSuccessStatusCode)
                        {
                            //Refer RoleId Controller in WebApi Controllers                
                            roleData = resultOfRoleId.Content.ReadAsAsync<List<RoleViewModel>>().Result;
                            var roleId = roleData.Select(e => e.Roleid).FirstOrDefault();
                            if (roleId == 0 | roleData is null)
                            {
                                return RedirectToAction("Customer");
                            }
                            else 
                            {
                                //based on the role id the specific page/view opens
                                switch (roleId)
                                {
                                    case 1:
                                        Session["RoleId"] = roleId;
                                        Session["Username"] = nameOfUser;
                                        return RedirectToAction("Admin");
                                    case 2:
                                        Session["RoleId"] = roleId;
                                        Session["Username"] = nameOfUser;
                                        return RedirectToAction("Employee");
                                    case 3:
                                        Session["RoleId"] = roleId;
                                        Session["Username"] = nameOfUser;
                                        return RedirectToAction("Customer");
                                }
                            }
                        }
                    }
                    else
                    {
                        
                        return View();
                    }
                }
                else
                {
                   
                    return View();
                }
                
            }
            return View();
        }
        //For Logout
        public RedirectResult Logout()
        {
            Session.Clear();
            return Redirect("https://localhost:44349/HomePage/Index");
        }

        //Customer Registration Part
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(UserRegister userRegister)
        {
            try
            {
                UsersViewModel userreg = new UsersViewModel()
                {
                    Username = userRegister.Username,Firstname = userRegister.Firstname, Lastname = userRegister.Lastname, Password = userRegister.Password
                };
                using (HttpClient client = new HttpClient())
                {

                        var result = client.PostAsJsonAsync("https://localhost:44307/api/usersn", userreg).Result;

                        if (result.IsSuccessStatusCode)
                        {
                            Session["Username"] = userRegister.Firstname + userRegister.Lastname;
                            return RedirectToAction("Customer");
                        }

                    
                }
                return View();
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Employee()
        {
            return View();
        }
        public ActionResult Admin()
        {
            return View();
        }
        public ActionResult Customer()
        {
            return View();
        }
        public ActionResult ErrorView()
        {
            return View();
        }
        public ActionResult AboutsUS()
        {
            return View();
        }
    }
}

IPLManagementSystemMVC/Views/HomePage/AboutsUS.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>IPL T20</title>
    <link rel="icon" href="~/Images/Logos/ipl logo 2.jpeg" type="image/image" style="height:16px;width:16px">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
    <style>
        #btn{
            font-size:15px;
        }
    </style>
</head>
<body style="background-color:bisque">
    <div class="row col-12">
        <div class="card col-4">
            <div class="card-body">
                <centre>
                    <h1 class="card-title" text-align:"centre">Akhil Chukkala</h1>
                </centre>
                <h3 class="card-text">
                    I am a From Peddapalli, Telangana<br />
                    Find out More about me!
                </h3>
                <a href="https://www.linkedin.com/in/akhil-chukkala-501091128/" target="_blank" class="btn btn-success" id="btn">Click Here!</a>
            </div>
            <br />
        </div>

        <div class="card col-4">
            <div class="card-body">
                <centre>
                    <h1 class="card-title" text-align:"centre">Jayaram Chinthala</h1>
                </centre>
                <h3 class="card-text">
                    I am a From Kodad, Suryapet<br />
                    Find out More about me!
                </h3>
                <a href="https://www.linkedin.com/in/jairam-chintalapati-969909202" target="_blank" class="btn btn-success" id="btn">Click Here!</a>
            </div>
            <br />
        </div>

        <div class="card col-4">
            <div class="card-body">
                <centre>
                    <h1 class="card-title" text-align:"centre">Vimal Anthony</h1>
                </centre>
                <h3 class="card-text">
                    I am a From Chennai, Tamilnadu<br />
                    Find out More about me!
                </h3>
                <a href="https://www.linkedin.com/in/vimal-antony-389bb5145" target="_blank" class="btn btn-success" id="btn">Click Here!</a>
            </div>
            <br />
        </div>

        <div class="card col-4">
            <div class="card-body">
                <centre>
                    <h1 class="card-title" text-align:"centre">Praveen Anmula</h1>
                </centre>
                <h3 class="card-text">
                    I am From Warangal, Telangana<br />
                    Find out More about me!
                </h3>
                <a href="https://www.linkedin.com/in/anumula-praveenreddy-370b3a1b2/" target="_blank" class="btn btn-success" id="btn">Click Here!</a>
            </div>
            <br />
        </div>

        <div class="card col-4">
            <div class="card-body">
                <centre>
                    <h1 class="card-title" text-align:"centre">Saiteja Gunjala</h1>
                </centre>
                <h3 class="card-text">
                    I am From Nirmal, Telangana<br />
                    Find out More about me!
                </h3>
                <a href="https://www.linkedin.com/in/gunjala-saiteja-04153b139/" target="_blank" class="btn btn-success" id="btn">Click Here!</a>
            </div>
            <br />
        </div>
    </div>
 
</body>
</html>

IPLManagementSystemMVC/Views/HomePage/Admin.cshtml
@{
    ViewBag.Title = "Admin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

IPLManagementSystemMVC/Views/HomePage/Customer.cshtml
@{
    ViewBag.Title = "Customer";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

<h2 id="heading"><u>Welcome To IPL Grandeur</u></h2>
<style>
    #heading {
        font-size: 30px;
        font-weight: bold;
        font-style: italic;
        font-family: Candara;
        color: indianred
    }
</style>
<body>
    <!--Carousels-->
    <div class="carousel slide" id="maindiv" data-ride="carousel" data-interval="3000">
        <!-- Indicators -->
        <ul class="carousel-indicators">
            <li data-target="#maindiv" data-slide-to="0" class="active"></li>
            <li data-target="#maindiv" data-slide-to="1"></li>
            <li data-target="#maindiv" data-slide-to="2"></li>
            <li data-target="#maindiv" data-slide-to="3"></li>
        </ul>
        <!-- Slide Show -->
        <div class="carousel-inner " style="padding-left:400px;background-color:azure">
            <div class="carousel-item active"><img src="~/Images/CSK.png" height="400"></div>
            <div class="carousel-item"><img src="~/Images/MI.png" height="400"></div>
            <div class="carousel-item" style="padding-left:100px"><img src="~/Images/RCB.png" height="400"></div>
            <div class="carousel-item"><img src="~/Images/SRH.png" height="400"></div>
        </div>
        <!-- left and right arrows-->
        <a class="carousel-control-prev" href="#maindiv" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#maindiv" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</body>

IPLManagementSystemMVC/Views/HomePage/Employee.cshtml
@{
    ViewBag.Title = "Employee";
    Layout = "~/Views/Shared/_EmployeeLayout.cshtml";
}

IPLManagementSystemMVC/Views/HomePage/ErrorView.cshtml
@{
    ViewBag.Title = "ErrorView";
    Layout = "~/Views/Shared/Error.cshtml";
}
<body>
    <div>
        <h1>You Are Unaouthorized To View This Page</h1>
        <p class="lead">Please Login Again</p>
        <p><a href="@Url.Action("Index","HomePage")" class="btn btn-danger" style="font-size:20px" >Click Here to Login</a></p>
    </div>
</body>

IPLManagementSystemMVC/Views/HomePage/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_HomePageLayout.cshtml";
}

<!DOCTYPE html>
<head>
    <style>
        .carousel-inner img {
            width: 100%;
            height: 500px;
        }
        #maindiv {
            padding-top: 50px;
        }
    </style>
</head>
<body>
    <!--Carousels-->
    <div class="carousel slide" id="maindiv" data-ride="carousel" data-interval="3000">
        <!-- Indicators -->
        <ul class="carousel-indicators">
            <li data-target="#maindiv" data-slide-to="0" class="active"></li>
            <li data-target="#maindiv" data-slide-to="1"></li>
            <li data-target="#maindiv" data-slide-to="2"></li>
            <li data-target="#maindiv" data-slide-to="3"></li>
            <li data-target="#maindiv" data-slide-to="4"></li>
            <li data-target="#maindiv" data-slide-to="5"></li>
        </ul>
        <!-- Slide Show -->
        <div class="carousel-inner">
            <div class="carousel-item active"><img src="~/Images/Logos/pic1.jpg"></div>
            <div class="carousel-item"><img src="~/Images/Logos/pic2.jpg"></div>
            <div class="carousel-item"><img src="~/Images/Logos/pic3.jpeg"></div>
            <div class="carousel-item"><img src="~/Images/Logos/pic4.jpg"></div>
            <div class="carousel-item"><img src="~/Images/Logos/pic5.jpg"></div>
            <div class="carousel-item"><img src="~/Images/Logos/pic6.jpg"></div>
        </div>
        <!-- left and right arrows-->
        <a class="carousel-control-prev" href="#maindiv" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#maindiv" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</body>

IPLManagementSystemMVC/Views/HomePage/Login.cshtml
@model IPLManagementSystemMVC.Models.LoginViewModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Login</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    <div class="form-group">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", required="required"}  })
            @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
        </div>
    </div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", required = "required" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>
    @*<div>
        <h4 style="color:red;font-size:15px;">@ViewBag.Message</h4>
    </div>*@
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Login" class="btn btn-default" />
        </div>
    </div>
</div>
}
<div>
    @Html.ActionLink("Go Back", "Index")
</div> @*&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*@
<div>
    New User?
    <a id="regirsterLink" href="@Url.Action("Register","HomePage")">Register</a>
    Here
</div>

IPLManagementSystemMVC/Views/HomePage/Register.cshtml
@model IPLManagementSystemMVC.Models.UserRegister

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Register Here</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control" , required = "Required"} })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", required = "Required" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control", required = "Required" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Firstname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Firstname, new { htmlAttributes = new { @class = "form-control", required = "Required" } })
                @Html.ValidationMessageFor(model => model.Firstname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Lastname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Lastname, new { htmlAttributes = new { @class = "form-control", required = "Required" } })
                @Html.ValidationMessageFor(model => model.Lastname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input style="font-size:15px" type="submit" value="Register" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Go Back", "Index")
</div>